# Duployan Translator: English <-> Duployan with Pronunciation
# Based on core vocab from PDFs and 449 new words
# Grammar: VSO order, tenses (past: 𛰃𛱂 'tow-uh', current: 𛰑 'th', future: 𛰋𛱁 'ra')
# Progressive: 𛰜𛱆 'see' before verb
# Negation: 𛰔𛱈 before verb
# Question: 𛰔𛱁 at end
# Plural: -𛰜 's'
# Adjectives after nouns
# Usage: translate_english_to_duployan("I will go home") or translate_duployan_to_english("𛰋𛱁 𛰅𛱄 𛱈 𛱈𛰉𛱕")

core_vocab = {
    'i': ('𛱈', 'eeh'),
    'you': ('𛰑𛱑', 'th-u'),
    'he': ('𛰀𛱆', 'hee'),
    'she': ('𛰆𛱆', 'lee'),
    'we': ('𛰉𛱆', 'vee'),
    'they': ('𛰑𛱒', 'th-eu'),
    'it': ('𛱋𛰑', 'eeh-th'),
    'him': ('𛱙𛰚', ''),
    'us': ('𛱗𛰜', ''),
    'me': ('𛰙𛱉', ''),
    'her': ('𛰗𛰘', ''),
    'them': ('𛰑𛱅', ''),
    'girl': ('𛰔𛱇𛰆', ''),
    'boy': ('𛰇𛱁𛱇', ''),
    'male': ('𛰙𛱅𛰆', ''),
    'female': ('𛰙𛱅𛰆𛰄𛱁', ''),
    'be': ('𛰑𛱁', 'tha'),  # Normalized verbs without 'to'
    'have': ('𛰙𛱆', 'mee'),
    'go': ('𛰅𛱄', 'ko'),
    'come': ('𛰅𛱁𛰙', 'kam'),
    'see': ('𛰜𛱆', 'see'),
    'say': ('𛰜𛱁𛰆', 'sal'),
    'speak': ('𛰜𛱁𛰆', 'sal'),
    'learn': ('𛰆𛱄𛰚', 'lon'),
    'know': ('𛰚𛱄', 'no'),
    'make': ('𛰙𛱁𛰅', 'mak'),
    'use': ('𛰑𛱕𛰜', 'th-oos'),
    'now': ('𛰑', 'th'),
    'before': ('𛰃𛱂', 'tow-uh'),
    'after': ('𛰋𛱁𛱁', 'ra-a'),
    'day': ('𛰋𛱄', 'ro'),
    'today': ('𛰋𛱄𛰑', 'ro-th'),
    'always': ('𛰜𛱄𛰆', 'sol'),
    'never': ('𛰚𛱁𛰜', 'nas'),
    'person': ('𛰙𛱆𛰚', 'meen'),
    'people': ('𛰙𛱆𛰚𛰜', 'meens'),
    'man': ('𛰙𛱆𛰚', 'meen'),
    'woman': ('𛰙𛱆𛰚𛱝', 'meen-wo'),
    'child': ('𛰇𛱁', 'ban'),
    'friend': ('𛰄𛱆𛰆', 'feel'),
    'world': ('𛰙𛱄𛰚', 'mon'),
    'language': ('𛰆𛱁𛰜𛱆', 'la-see'),
    'word': ('𛰜𛱄𛰋', 'sor'),
    'meaning': ('𛰙𛱆𛰜', 'mees'),
    'name': ('𛰚𛱁𛰙', 'nam'),
    'truth': ('𛰃𛱁𛰜', 'tas'),
    'idea': ('𛱁𛰆𛱆', 'a-lee'),
    'good': ('𛰄𛱄', 'fo'),
    'bad': ('𛰄𛱁𛰜', 'fas'),
    'big': ('𛰅𛱁', 'ka'),
    'small': ('𛰜𛱁𛰆', 'sal'),
    'new': ('𛰚𛱕', 'noo'),
    'old': ('𛰋𛱄𛰆', 'rol'),
    'and': ('𛰜', 's'),
    'or': ('𛰋', 'r'),
    'not': ('𛰚', 'n'),
    'yes': ('𛰜𛱆', 'see'),
    'no': ('𛰚𛱄', 'no'),
}

# New words (449 from previous generation, normalized to lower case)
new_vocab = {
    'the': ('𛰃𛱕𛰇', 'toob'),
    'of': ('𛰃𛱁𛰚', 'tan'),
    'to': ('𛱒𛰃𛱑', 'eutu'),
    'a': ('𛰄𛱂𛰑', 'fowuhth'),
    'in': ('𛰙𛱋', 'meeh'),
    'is': ('𛱆', 'ee'),
    'that': ('𛱈𛰆𛱋', 'eehleeh'),
    'was': ('𛱄𛰅𛱄', 'oko'),
    'for': ('𛰀𛱒', 'heu'),
    'are': ('𛰄𛱝𛰑', 'fwoth'),
    'with': ('𛱈𛰀𛱈', 'eehheeh'),
    'as': ('𛱒𛰚𛱂', 'eunowuh'),
    'his': ('𛰇𛱒𛰑', 'beuth'),
    'at': ('𛱈𛰇', 'eehb'),
    'one': ('𛰑𛱄', 'tho'),
    'this': ('𛰅𛱂𛰇', 'kowuhb'),
    'from': ('𛱂𛰀𛱈', 'owuhheeh'),
    'had': ('𛱋𛰆', 'eehl'),
    'by': ('𛰄𛱝𛰋', 'fwor'),
    'hot': ('𛱈𛰑𛱝', 'eehthwo'),
    'but': ('𛰋𛱈', 'reeh'),
    'some': ('𛱄𛰚', 'on'),
    'what': ('𛱋𛰃𛱄', 'eehto'),
    'there': ('𛱑𛰙', 'um'),
    'can': ('𛰀𛱆𛰉', 'heev'),
    'out': ('𛰜𛱈', 'seeh'),
    'other': ('𛰇𛱕𛰜', 'boos'),
    'were': ('𛱝𛰚𛱝', 'wonwo'),
    'all': ('𛱆𛰃', 'eet'),
    'your': ('𛱆𛰜𛱄', 'eeso'),
    'when': ('𛰆𛱑𛰜', 'lus'),
    'up': ('𛰙𛱋𛰃', 'meeht'),
    'how': ('𛱑𛰇𛱆', 'ubee'),
    'said': ('𛰀𛱕𛰇', 'hoob'),
    'an': ('𛰜𛱑', 'su'),
    'each': ('𛰜𛱂', 'sowuh'),
    'which': ('𛰋𛱋', 'reeh'),
    'do': ('𛱆𛰇', 'eeb'),
    'their': ('𛰇𛱝𛰃', 'bwot'),
    'time': ('𛰑𛱋', 'theeh'),
    'if': ('𛰇𛱈𛰜', 'beehs'),
    'will': ('𛱄𛰙', 'om'),
    'way': ('𛰙𛱄𛰄', 'mof'),
    'about': ('𛱂𛰙', 'owuhm'),
    'many': ('𛱒𛰅𛱄', 'euko'),
    'then': ('𛰙𛱈', 'meeh'),
    'would': ('𛱆𛰇𛱈', 'eebeeh'),
    'write': ('𛰚𛱕𛰋', 'noor'),
    'like': ('𛰋𛱂', 'rowuh'),
    'so': ('𛰋𛱂𛰙', 'rowuhm'),
    'these': ('𛰚𛱆', 'nee'),
    'long': ('𛰋𛱑𛰙', 'rum'),
    'thing': ('𛰇𛱋', 'beeh'),
    'two': ('𛱕𛰙', 'oom'),
    'has': ('𛱂𛰜', 'owuhs'),
    'look': ('𛰇𛱁𛰉', 'bav'),
    'more': ('𛱒𛰅𛱋', 'eukeeh'),
    'could': ('𛱝𛰜', 'wos'),
    'did': ('𛰋𛱋𛰙', 'reehm'),
    'my': ('𛰜𛱕𛰄', 'soof'),
    'sound': ('𛱈𛰉𛱂', 'eehvowuh'),
    'most': ('𛱋𛰋', 'eehr'),
    'number': ('𛱒𛰄𛱁', 'eufa'),
    'who': ('𛰆𛱒', 'leu'),
    'over': ('𛱄𛰉', 'ov'),
    'water': ('𛰑𛱈', 'theeh'),
    'than': ('𛱁𛰅', 'ak'),
    'call': ('𛱄𛰉𛱝', 'ovwo'),
    'first': ('𛰇𛱈𛰃', 'beeht'),
    'may': ('𛰙𛱆𛰄', 'meef'),
    'down': ('𛰇𛱑𛰅', 'buk'),
    'side': ('𛰙𛱋𛰙', 'meehm'),
    'been': ('𛱂𛰀𛱄', 'owuhho'),
    'find': ('𛰀𛱋𛰇', 'heehb'),
    'any': ('𛱈𛰀𛱒', 'eehheu'),
    'work': ('𛰚𛱁', 'na'),
    'part': ('𛱂𛰀', 'owuhh'),
    'take': ('𛱁𛰃', 'at'),
    'get': ('𛱕𛰋𛱒', 'ooreu'),
    'place': ('𛱆𛰉𛱝', 'eevwo'),
    'made': ('𛰄𛱕', 'foo'),
    'live': ('𛰀𛱄𛰜', 'hos'),
    'where': ('𛰄𛱁', 'fa'),
    'little': ('𛱈𛰇𛱋', 'eehbeeh'),
    'only': ('𛰆𛱁𛱄', 'alo'),
    'round': ('𛰋𛱈𛰇', 'reehb'),
    'year': ('𛱁𛰇𛱈', 'abeeh'),
    'came': ('𛰙𛱁𛰃', 'mat'),
    'show': ('𛱝𛰆𛱋', 'woleeh'),
    'every': ('𛱒𛰚', 'eun'),
    'give': ('𛰉𛱒', 'veu'),
    'our': ('𛱄𛰆𛱁', 'ola'),
    'under': ('𛰆𛱒𛰃', 'leut'),
    'very': ('𛰇𛱝𛰇', 'bwob'),
    'through': ('𛰙𛱁𛰙', 'mam'),
    'just': ('𛱈𛰙𛱆', 'eehmee'),
    'form': ('𛰆𛱁𛰙', 'lam'),
    'much': ('𛱂𛰑', 'owuhth'),
    'great': ('𛱋𛰀', 'eehh'),
    'think': ('𛱂𛰙𛱁', 'owuhma'),
    'help': ('𛰇𛱈𛰋', 'beehr'),
    'low': ('𛰋𛱈𛰑', 'reehth'),
    'line': ('𛰆𛱂𛰅', 'lowuhk'),
    'turn': ('𛱂𛰇', 'owuhb'),
    'cause': ('𛱆𛰜𛱒', 'eeseu'),
    'same': ('𛰆𛱋', 'leeh'),
    'mean': ('𛱝𛰚', 'won'),
    'differ': ('𛱂', 'owuh'),
    'move': ('𛱑𛰃𛱆', 'utee'),
    'right': ('𛰚𛱑𛰜', 'nus'),
    'too': ('𛱒𛰙', 'eum'),
    'does': ('𛰑𛱒𛰑', 'theuth'),
    'tell': ('𛱝𛰅𛱆', 'wokee'),
    'sentence': ('𛱝𛰀𛱄', 'woho'),
    'set': ('𛰃𛱒', 'teu'),
    'three': ('𛱈𛰜𛱒', 'eehseu'),
    'want': ('𛰙𛱝𛰑', 'mwoth'),
    'air': ('𛱝𛰆', 'wol'),
    'well': ('𛱆𛰉𛱈', 'eeveeh'),
    'also': ('𛱁𛰉', 'av'),
    'play': ('𛱒𛰃𛱆', 'eutee'),
    'end': ('𛰃𛱄𛰅', 'tok'),
    'put': ('𛰅𛱄𛰇', 'kob'),
    'home': ('𛱈𛰉𛱕', 'eehvoo'),
    'read': ('𛱕𛰄', 'oof'),
    'hand': ('𛱕𛰉', 'oov'),
    'port': ('𛰚𛱝𛰋', 'nwor'),
    'large': ('𛱒𛰉', 'euv'),
    'spell': ('𛰑𛱂𛰆', 'thowuhl'),
    'add': ('𛰅𛱆', 'kee'),
    'even': ('𛱋𛰑𛱒', 'eehtheu'),
    'land': ('𛱝𛰃', 'wot'),
    'here': ('𛱈𛰋', 'eehr'),
    'must': ('𛱆𛰃𛱆', 'eetee'),
    'high': ('𛰆𛱋𛰙', 'leehm'),
    'such': ('𛱋𛰀𛱋', 'eehheeh'),
    'follow': ('𛱈𛰀', 'eehh'),
    'act': ('𛰙𛱆𛰋', 'meer'),
    'why': ('𛰃𛱆𛰚', 'teen'),
    'ask': ('𛰅𛱂', 'kowuh'),
    'men': ('𛰙𛱁𛰀', 'mah'),
    'change': ('𛰉𛱝𛰉', 'vwov'),
    'went': ('𛰃𛱕', 'too'),
    'light': ('𛰇𛱂', 'bowuh'),
    'kind': ('𛰚𛱑', 'nu'),
    'off': ('𛱁𛰀𛱒', 'aheu'),
    'need': ('𛰜𛱆𛰉', 'seev'),
    'house': ('𛰜𛱑𛰚', 'sun'),
    'picture': ('𛰜𛱝𛰑', 'swoth'),
    'try': ('𛱆𛰇𛱕', 'eeboo'),
    'again': ('𛰚𛱋𛰚', 'neehn'),
    'animal': ('𛱑𛰚𛱑', 'unu'),
    'point': ('𛰜𛱁𛰚', 'san'),
    'mother': ('𛱝𛰋', 'wor'),
    'near': ('𛱒𛰜', 'eus'),
    'build': ('𛱑𛰇𛱂', 'ubowuh'),
    'self': ('𛰃𛱂𛰅', 'towuhk'),
    'earth': ('𛱄𛰃𛱄', 'oto'),
    'father': ('𛱋𛰚𛱒', 'eehneu'),
    'head': ('𛰇𛱒𛰋', 'beur'),
    'stand': ('𛰑𛱒𛰑', 'theuth'),
    'own': ('𛰑𛱁𛰚', 'than'),
    'page': ('𛱁𛰃𛱈', 'ateeh'),
    'should': ('𛱈𛰜', 'eehs'),
    'country': ('𛱄𛰃', 'ot'),
    'found': ('𛰉𛱋', 'veeh'),
    'answer': ('𛰚𛱋', 'neeh'),
    'school': ('𛰚𛱑𛰜', 'nus'),
    'grow': ('𛱑𛰚𛱋', 'uneeh'),
    'study': ('𛰜𛱝', 'swo'),
    'still': ('𛱕𛰇𛱑', 'oobu'),
    'plant': ('𛱁𛰚', 'an'),
    'cover': ('𛱂𛰆𛱂', 'owuhlowuh'),
    'food': ('𛰃𛱆𛰉', 'teev'),
    'sun': ('𛰃𛱆𛰉', 'teev'),
    'four': ('𛱂𛰙𛱕', 'owuhmoo'),
    'thought': ('𛰃𛱁', 'ta'),
    'let': ('𛱒𛰙𛱑', 'eumu'),
    'keep': ('𛱒𛰚𛱝', 'eunwo'),
    'eye': ('𛱈𛰉𛱝', 'eehvwo'),
    'last': ('𛱆𛰙𛱆', 'eemee'),
    'door': ('𛰜𛱄𛰉', 'sov'),
    'between': ('𛰆𛱁', 'la'),
    'city': ('𛰋𛱁', 'ra'),
    'tree': ('𛰃𛱁𛰙', 'tam'),
    'cross': ('𛰃𛱁𛰃', 'tat'),
    'since': ('𛰇𛱑𛰃', 'but'),
    'hard': ('𛱕𛰃', 'oot'),
    'start': ('𛱆𛰜𛱁', 'eesa'),
    'might': ('𛰉𛱕𛰜', 'voos'),
    'story': ('𛰇𛱄𛰇', 'bob'),
    'saw': ('𛰃𛱋𛰅', 'teehk'),
    'far': ('𛱝𛰉𛱑', 'wovu'),
    'sea': ('𛱕𛰚', 'oon'),
    'draw': ('𛰚𛱝', 'nwo'),
    'left': ('𛱕𛰚𛱒', 'ooneu'),
    'late': ('𛰇𛱑𛰇', 'bub'),
    'run': ('𛰋𛱕𛰜', 'roos'),
    'don’t': ('𛰚𛱋𛰅', 'neehk'),
    'while': ('𛱒𛰅', 'euk'),
    'press': ('𛱑𛰀𛱆', 'uhee'),
    'night': ('𛰚𛱝𛰄', 'nwof'),
    'real': ('𛰄𛱋', 'feeh'),
    'life': ('𛰋𛱈𛰅', 'reehk'),
    'few': ('𛰋𛱑', 'ru'),
    'stop': ('𛰙𛱒', 'meu'),
    'open': ('𛰜𛱑𛰑', 'suth'),
    'seem': ('𛱝', 'wo'),
    'together': ('𛰄𛱝', 'fwo'),
    'white': ('𛰚𛱒𛰃', 'neut'),
    'children': ('𛱄𛰇𛱑', 'obu'),
    'begin': ('𛱕𛰃𛱆', 'ootee'),
    'got': ('𛰋𛱁𛰇', 'rab'),
    'walk': ('𛰆𛱕𛰜', 'loos'),
    'example': ('𛱁', 'a'),
    'ease': ('𛰄𛱆', 'fee'),
    'paper': ('𛰀𛱕𛰆', 'hool'),
    'often': ('𛰃𛱄𛰀', 'toh'),
    'music': ('𛰜𛱒𛰃', 'seut'),
    'those': ('𛱝𛰑𛱈', 'wotheeh'),
    'both': ('𛰇𛱈', 'beeh'),
    'mark': ('𛱝𛰉𛱁', 'wova'),
    'book': ('𛰅𛱈', 'keeh'),
    'letter': ('𛰉𛱝𛰋', 'vwor'),
    'until': ('𛰚𛱂𛰇', 'nowuhb'),
    'mile': ('𛱄𛰇𛱒', 'obeu'),
    'river': ('𛱄𛰆𛱑', 'olu'),
    'car': ('𛰃𛱆𛰆', 'teel'),
    'feet': ('𛰇𛱄', 'bo'),
    'second': ('𛰑𛱂𛰜', 'thowuhs'),
    'group': ('𛱄', 'o'),
    'carry': ('𛰆𛱂𛰉', 'lowuhv'),
    'took': ('𛱕𛰆', 'ool'),
    'rain': ('𛱑𛰋𛱂', 'urowuh'),
    'eat': ('𛱋𛰚𛱁', 'eehna'),
    'room': ('𛱕𛰙𛱕', 'oomoo'),
    'began': ('𛱈𛰄', 'eehf'),
    'fish': ('𛰜𛱄𛰜', 'sos'),
    'mountain': ('𛰅𛱕𛰆', 'kool'),
    'north': ('𛱁𛰇', 'ab'),
    'once': ('𛱋𛰚', 'eehn'),
    'base': ('𛰋𛱋𛰋', 'reehr'),
    'hear': ('𛱂𛰄𛱑', 'owuhfu'),
    'horse': ('𛱒𛰅𛱕', 'eukoo'),
    'cut': ('𛱆𛰚', 'een'),
    'sure': ('𛱋𛰋𛱁', 'eehra'),
    'watch': ('𛰑𛱆', 'thee'),
    'color': ('𛱕𛰋', 'oor'),
    'face': ('𛱋𛰙', 'eehm'),
    'wood': ('𛱋𛰚𛱈', 'eehneeh'),
    'main': ('𛰋𛱒', 'reu'),
    'enough': ('𛱄𛰜𛱝', 'oswo'),
    'plain': ('𛰃𛱂𛰇', 'towuhb'),
    'usual': ('𛰀𛱈𛰅', 'heehk'),
    'young': ('𛰀𛱈', 'heeh'),
    'ready': ('𛱄𛰅', 'ok'),
    'above': ('𛱋𛰉', 'eehv'),
    'ever': ('𛰃𛱝', 'two'),
    'red': ('𛱒', 'eu'),
    'list': ('𛰙𛱆𛰇', 'meeb'),
    'though': ('𛱈𛰅', 'eehk'),
    'feel': ('𛱄𛰅𛱆', 'okee'),
    'talk': ('𛱑𛰃', 'ut'),
    'bird': ('𛰆𛱕𛰑', 'looth'),
    'soon': ('𛱁𛰇𛱋', 'abeeh'),
    'body': ('𛱕𛰜', 'oos'),
    'dog': ('𛰀𛱄𛰉', 'hov'),
    'family': ('𛰃𛱈', 'teeh'),
    'direct': ('𛰆𛱋𛰑', 'leehth'),
    'pose': ('𛱂𛰉', 'owuhv'),
    'leave': ('𛱂𛰄', 'owuhf'),
    'song': ('𛱈𛰜𛱁', 'eehsa'),
    'measure': ('𛱁𛰄𛱝', 'afwo'),
    'state': ('𛱈𛰉𛱈', 'eehveeh'),
    'product': ('𛱆𛰚𛱄', 'eeno'),
    'black': ('𛱝𛰄𛱆', 'wofee'),
    'short': ('𛱁𛰚𛱑', 'anu'),
    'numeral': ('𛱄𛰋', 'or'),
    'class': ('𛰋𛱁𛰀', 'rah'),
    'wind': ('𛱝𛰀', 'woh'),
    'question': ('𛰑𛱝', 'thwo'),
    'happen': ('𛰋𛱆𛰉', 'reev'),
    'complete': ('𛰆𛱈𛰀', 'leehh'),
    'ship': ('𛱄𛰜', 'os'),
    'area': ('𛱝𛰙', 'wom'),
    'half': ('𛰑𛱋𛰉', 'theehv'),
    'rock': ('𛰙𛱆𛰆', 'meel'),
    'order': ('𛱋𛰜', 'eehs'),
    'fire': ('𛱆𛰉𛱕', 'eevoo'),
    'south': ('𛰉𛱂𛰋', 'vowuhr'),
    'problem': ('𛰚𛱈', 'neeh'),
    'piece': ('𛱆𛰀', 'eeh'),
    'told': ('𛱁𛰆', 'al'),
    'knew': ('𛰇𛱑', 'bu'),
    'pass': ('𛰙𛱈𛰆', 'meehl'),
    'farm': ('𛰑𛱕𛰑', 'thooth'),
    'top': ('𛰋𛱕', 'roo'),
    'whole': ('𛱝𛰄𛱈', 'wofeeh'),
    'king': ('𛱋𛰅𛱆', 'eehkee'),
    'size': ('𛱄𛰇𛱂', 'obowuh'),
    'heard': ('𛰅𛱝𛰑', 'kwoth'),
    'best': ('𛰉𛱈', 'veeh'),
    'hour': ('𛰚𛱂𛰙', 'nowuhm'),
    'better': ('𛰜𛱑𛰋', 'sur'),
    'true': ('𛰇𛱑𛰄', 'buf'),
    'during': ('𛰉𛱕', 'voo'),
    'hundred': ('𛱑𛰙𛱒', 'umeu'),
    'am': ('𛰃𛱄', 'to'),
    'remember': ('𛱁𛰄', 'af'),
    'step': ('𛱑𛰜𛱝', 'uswo'),
    'early': ('𛱈𛰜𛱄', 'eehso'),
    'hold': ('𛰆𛱈𛰑', 'leehth'),
    'west': ('𛰃𛱆', 'tee'),
    'ground': ('𛱒𛰚𛱒', 'euneu'),
    'interest': ('𛱝𛰑', 'woth'),
    'reach': ('𛱄𛰑𛱑', 'othu'),
    'fast': ('𛰉𛱋𛰃', 'veeht'),
    'five': ('𛱑', 'u'),
    'sing': ('𛱝𛰑𛱑', 'wothu'),
    'listen': ('𛱁𛰚𛱈', 'aneeh'),
    'six': ('𛱒𛰀𛱁', 'euha'),
    'table': ('𛰙𛱈𛰃', 'meeht'),
    'travel': ('𛱒𛰙𛱁', 'euma'),
    'less': ('𛱕𛰇', 'oob'),
    'morning': ('𛰇𛱆𛰋', 'beer'),
    'ten': ('𛱕𛰅𛱕', 'ookoo'),
    'simple': ('𛰅𛱆𛰑', 'keeth'),
    'several': ('𛱆𛰜', 'ees'),
    'vowel': ('𛱄𛰆𛱈', 'oleeh'),
    'toward': ('𛱋𛰅', 'eehk'),
    'war': ('𛰇𛱄𛰀', 'boh'),
    'lay': ('𛰃𛱂𛰋', 'towuhr'),
    'against': ('𛰙𛱕𛰆', 'mool'),
    'pattern': ('𛱑𛰆𛱄', 'ulo'),
    'slow': ('𛰇𛱆', 'bee'),
    'center': ('𛰉𛱆𛰃', 'veet'),
    'love': ('𛰅𛱆𛰆', 'keel'),
    'money': ('𛱕𛰇𛱝', 'oobwo'),
    'serve': ('𛰚𛱂', 'nowuh'),
    'appear': ('𛱑𛰅', 'uk'),
    'road': ('𛰀𛱁', 'ha'),
    'map': ('𛱕𛰀', 'ooh'),
    'science': ('𛰆𛱄', 'lo'),
    'rule': ('𛱕𛰄𛱆', 'oofee'),
    'govern': ('𛰑𛱕', 'thoo'),
    'pull': ('𛱂𛰉𛱂', 'owuhvowuh'),
    'cold': ('𛱈𛰚', 'eehn'),
    'notice': ('𛱕𛰇𛱁', 'ooba'),
    'voice': ('𛱄𛰆', 'ol'),
    'fall': ('𛱁𛰙𛱄', 'amo'),
    'power': ('𛰙𛱁', 'ma'),
    'town': ('𛱈𛰃', 'eeht'),
    'fine': ('𛱑𛰜𛱁', 'usa'),
    'certain': ('𛱈𛰑𛱈', 'eehtheeh'),
    'fly': ('𛱆𛰙', 'eem'),
    'unit': ('𛰀𛱄', 'ho'),
    'lead': ('𛰄𛱋𛰜', 'feehs'),
    'cry': ('𛰜𛱑𛰜', 'sus'),
    'dark': ('𛰚𛱄𛰄', 'nof'),
    'machine': ('𛰙𛱕', 'moo'),
    'note': ('𛱕𛰙𛱄', 'oomo'),
    'wait': ('𛱈𛰅𛱄', 'eehko'),
    'plan': ('𛱕𛰇𛱒', 'oobeu'),
    'figure': ('𛰆𛱑', 'lu'),
    'star': ('𛰇𛱝𛰀', 'bwoh'),
    'box': ('𛰄𛱋𛰑', 'feehth'),
    'noun': ('𛰋𛱑𛰆', 'rul'),
    'field': ('𛱝𛰄𛱕', 'wofoo'),
    'rest': ('𛱕𛰑', 'ooth'),
    'correct': ('𛱄𛰉𛱂', 'ovowuh'),
    'able': ('𛰅𛱝𛰙', 'kwom'),
    'pound': ('𛱒𛰃', 'eut'),
    'done': ('𛱕𛰚𛱈', 'ooneeh'),
    'beauty': ('𛱆𛰋', 'eer'),
    'drive': ('𛱑𛰇', 'ub'),
    'stood': ('𛱝𛰅', 'wok'),
    'contain': ('𛱄𛰇', 'ob'),
    'front': ('𛰃𛱁𛰄', 'taf'),
    'teach': ('𛱈𛰉', 'eehv'),
    'week': ('𛱈𛰑', 'eehth'),
    'final': ('𛰙𛱝', 'mwo'),
    'gave': ('𛱄𛰅𛱝', 'okwo'),
    'green': ('𛰆𛱝', 'lwo'),
    'oh': ('𛱝𛰑𛱈', 'wotheeh'),
    'quick': ('𛱆𛰉𛱂', 'eevowuh'),
    'develop': ('𛱝𛰆𛱁', 'wola'),
    'sleep': ('𛱒𛰉𛱈', 'euveeh'),
    'warm': ('𛰙𛱆𛰆', 'meel'),
    'free': ('𛰀𛱑𛰑', 'huth'),
    'minute': ('𛱋', 'eeh'),
    'strong': ('𛰄𛱒', 'feu'),
    'special': ('𛱝𛰃𛱆', 'wotee'),
    'mind': ('𛰆𛱆𛰙', 'leem'),
    'behind': ('𛰃𛱑', 'tu'),
    'clear': ('𛰙𛱂', 'mowuh'),
    'tail': ('𛱒𛰅𛱝', 'eukwo'),
    'produce': ('𛰋𛱝𛰚', 'rwon'),
    'fact': ('𛱒𛰑', 'euth'),
    'street': ('𛰜𛱕𛰉', 'soov'),
    'inch': ('𛰜𛱆𛰉', 'seev'),
    'lot': ('𛱋𛰇𛱝', 'eehbwo'),
    'nothing': ('𛰚𛱒𛰋', 'neur'),
    'course': ('𛱆𛰉', 'eev'),
    'stay': ('𛰑𛱂', 'thowuh'),
    'wheel': ('𛱕𛰉𛱆', 'oovee'),
    'full': ('𛱈𛰙', 'eehm'),
    'force': ('𛰄𛱑𛰋', 'fur'),
    'blue': ('𛱄𛰙𛱂', 'omowuh'),
    'object': ('𛱂𛰃', 'owuht'),
    'decide': ('𛱑𛰋𛱁', 'ura'),
    'surface': ('𛱆𛰅', 'eek'),
    'deep': ('𛱂𛰋', 'owuhr'),
    'moon': ('𛰃𛱋', 'teeh'),
    'island': ('𛰇𛱈𛰙', 'beehm'),
    'foot': ('𛱕', 'oo'),
    'yet': ('𛱆𛰆', 'eel'),
    'busy': ('𛰑𛱝𛰋', 'thwor'),
    'test': ('𛰃𛱒𛰄', 'teuf'),
    'record': ('𛱄𛰉𛱄', 'ovo'),
    'boat': ('𛰇𛱄𛰋', 'bor'),
    'common': ('𛱝𛰆𛱄', 'wolo'),
    'gold': ('𛱁𛰙𛱂', 'amowuh'),
    'possible': ('𛱂𛰑𛱈', 'owuhtheeh'),
    'plane': ('𛱄𛰙𛱕', 'omoo'),
    'age': ('𛰙𛱄', 'mo'),
    'dry': ('𛱆𛰙', 'eem'),
    'wonder': ('𛰆𛱂', 'lowuh'),
    'laugh': ('𛱑𛰆𛱂', 'ulowuh'),
    'thousand': ('𛰙𛱂𛰉', 'mowuhv'),
    'ago': ('𛰇𛱈𛰆', 'beehl'),
    'ran': ('𛱁𛰀', 'ah'),
    'check': ('𛰋𛱕𛰅', 'rook'),
    'game': ('𛰋𛱝', 'rwo'),
    'shape': ('𛰙𛱁𛰋', 'mar'),
    'miss': ('𛱁𛰙𛱈', 'ameeh'),
    'brought': ('𛱕𛰅𛱈', 'ookeeh'),
    'heat': ('𛰆𛱑𛰆', 'lul'),
    'snow': ('𛰅𛱝', 'kwo'),
    'bed': ('𛰙𛱕𛰇', 'moob'),
    'bring': ('𛰇𛱒', 'beu'),
    'sit': ('𛰄𛱈', 'feeh'),
    'perhaps': ('𛱑𛰆', 'ul'),
    'fill': ('𛱈𛰆', 'eehl'),
    'east': ('𛱕𛰚𛱝', 'oonwo'),
    'weight': ('𛰅𛱑𛰉', 'kuv'),
    'among': ('𛱒𛰀𛱒', 'euheu'),
}

core_vocab.update(new_vocab)

# Reverse for Duployan to English
dup_to_eng = {v[0]: k for k, v in core_vocab.items() if v[0]}

# Particles
tense_particles = {
    'past': ('𛰃𛱂', 'tow-uh'),
    'current': ('𛰑', 'th'),
    'future': ('𛰋𛱁', 'ra'),
}
progressive = ('𛰜𛱆', 'see')
plural_suffix = ('𛰜', 's')
question_marker = ('𛰔𛱁', '')
negation = ('𛰔𛱈', '')
emphasis = ('𛰛𛱁', '')

# Helper to detect tense from English sentence (simple keyword check)
def detect_tense(words):
    if any(w in ['was', 'went', 'had', 'did', 'came', 'made', 'took', 'began'] for w in words):
        return 'past'
    elif any(w in ['will', 'would'] for w in words):
        return 'future'
    return 'current'

# English to Duployan
def translate_english_to_duployan(sentence):
    words = sentence.lower().replace('.', '').replace(',', '').split()
    tense = detect_tense(words)
    # Simple VSO: find verb, subject, object (assume first noun/pron subject, verb, rest object)
    subject = None
    verb = None
    object_ = []
    for w in words:
        if w in core_vocab:
            if not subject and w in ['i', 'you', 'he', 'she', 'we', 'they', 'it', 'him', 'us', 'me', 'her', 'them', 'person', 'people', 'man', 'woman', 'child', 'friend', 'girl', 'boy']:
                subject = w
            elif not verb and w in ['be', 'have', 'go', 'come', 'see', 'say', 'speak', 'learn', 'know', 'make', 'use', 'go', 'come', 'see', 'say', 'learn', 'know', 'make', 'use', 'write', 'like', 'do', 'will', 'would', 'find', 'take', 'get', 'give', 'tell', 'call', 'ask', 'change', 'need', 'try', 'build', 'stand', 'let', 'keep', 'start', 'run', 'hear', 'cut', 'watch', 'eat', 'feel', 'talk', 'sing', 'listen', 'carry', 'serve', 'appear', 'govern', 'pull', 'fall', 'lead']:
                verb = w
            else:
                object_.append(w)
    if not subject or not verb:
        return 'Unable to parse sentence (missing subject or verb)', ''

    subject_dup, subject_pron = core_vocab.get(subject, ('?', '?'))
    verb_dup, verb_pron = core_vocab.get(verb, ('?', '?'))
    object_dup = ' '.join(core_vocab.get(o, ('?', '?'))[0] for o in object_)
    object_pron = '-'.join(core_vocab.get(o, ('?', '?'))[1] for o in object_)

    tense_part, tense_pron = tense_particles[tense]

    # Build Duployan: tense + verb + subject + object
    dup_sentence = ' '.join(filter(None, [tense_part, verb_dup, subject_dup, object_dup]))
    pron_sentence = '-'.join(filter(None, [tense_pron, verb_pron, subject_pron, object_pron]))

    return dup_sentence, pron_sentence

# Duployan to English
def translate_duployan_to_english(dup_sentence):
    words = dup_sentence.split()
    if len(words) < 2:
        return 'Invalid Duployan sentence', ''

    tense_part = words[0]
    verb_dup = words[1]
    subject_dup = words[2]
    object_dup = ' '.join(words[3:])

    tense = next((k for k, v in tense_particles.items() if v[0] == tense_part), 'current')
    verb_eng = dup_to_eng.get(verb_dup, '?')
    subject_eng = dup_to_eng.get(subject_dup, '?')
    object_eng = ' '.join(dup_to_eng.get(o, '?') for o in object_dup.split())

    # SVO
    eng_sentence = f"{subject_eng} {tense} {verb_eng} {object_eng}".strip()

    return eng_sentence, ''  # No pronun for English

# Example usage
print('English to Duployan:')
dup, pron = translate_english_to_duployan('I go home')
print('Duployan:', dup)
print('Pronunciation:', pron)

print('\nDuployan to English:')
eng, _ = translate_duployan_to_english('𛰑 𛰅𛱄 𛱈 𛱈𛰉𛱕')
print('English:', eng)
